AMGI.PremiumCalculator.Project/Models/PremiumUnitAmount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMGI.PremiumCalculator.Project.Models
{
    public class PremiumUnitAmount
    {
        public Guid Id { get; set; }
        public Guid TravelInsuranceTypeID { get; set; }
        public string TravelInsuranceTypeCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Days { get; set; }
        public Decimal Amount { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}

AMGI.PremiumCalculator.Project/Models/PremiumUnitAmountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMGI.PremiumCalculator.Project.Models
{
    public class PremiumUnitAmountViewModel
    {
        public Guid Id { get; set; }
        public Guid TravelInsuranceTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Days { get; set; }
        public Decimal Amount { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string TravelInsuranceTypeName { get; set; }
    }
}

AMGI.PremiumCalculator.Project/Models/TravelInsuranceType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMGI.PremiumCalculator.Project.Models
{
    public class TravelInsuranceType
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Term { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    }
}

AMGI.PremiumCalculator.Project/Controllers/TravelSetupController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AMGI.PremiumCalculator.Project.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;

namespace AMGI.PremiumCalculator.Project.Controllers
{
    public class TravelSetupController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        public ISession session;
        MainDBContext _db = new MainDBContext();
        public TravelSetupController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                return View();
            }
        }

        #region Travel Insurance Type

        public IActionResult TravelInsuranceType()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                TravelInsuranceType travelInsuranceType = new TravelInsuranceType();
                var travelInsuranceTypesList = _db.TravelInsuranceType.ToList();
                ViewBag.TravelInsuranceTypesList = travelInsuranceTypesList;
                return View();
            }
        }

        public IActionResult CreateTravelInsuranceType(TravelInsuranceType travelInsuranceType)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult SaveTravelInsuranceType(TravelInsuranceType model)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                try
                {
                    if (model.Id == Guid.Empty)
                    {
                        model.Id = Guid.NewGuid();
                        model.CreatedDate = DateTime.Now;
                        model.ModifiedDate = DateTime.Now;
                        session = HttpContext.Session;
                        string username = session.GetString("username");
                        model.CreatedBy = username;
                        model.ModifiedBy = username;

                        _db.Entry(model).State = EntityState.Added;
                        _db.SaveChanges();

                        ViewBag.Message = "Save Successful.";
                        return RedirectToAction("TravelInsuranceType");

                    }
                    else
                    {
                        if (ModelState.IsValid)
                        {
                            session = HttpContext.Session;
                            model.ModifiedBy = session.GetString("username");
                            model.ModifiedDate = DateTime.Now;

                            _db.Update(model);
                            _db.SaveChanges();

                            ViewBag.Message = "Save Successful.";
                        }
                    }
                }
                catch (DbUpdateException)
                {
                    TempData["Message"] = "Error in Saving Process.";
                    return RedirectToAction("CreateTravelInsuranceType", model);
                    //throw ex;
                }
            }
            TempData["Message"] = "Save Successful";
            return RedirectToAction("TravelInsuranceType");       
        }

        public IActionResult ImportTravelInsuranceTypeList()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                return View();
            }
        }

        [HttpPost]
        [Route("ImportTravelInsuranceType")]
        public IActionResult ImportExcelData(IFormFile reportfile)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                string folderName = "ImportedFiles";
                string webRootPath = _hostingEnvironment.WebRootPath;
                string newPath = Path.Combine(webRootPath, folderName);
                // Delete Files from Directory
                System.IO.DirectoryInfo di = new DirectoryInfo(newPath);
                foreach (FileInfo filesDelete in di.GetFiles())
                {
                    filesDelete.Delete();
                }// End Deleting files form directories

                if (!Directory.Exists(newPath))// Crate New Directory if not exist as per the path
                {
                    Directory.CreateDirectory(newPath);
                }
                var fiName = Guid.NewGuid().ToString() + Path.GetExtension(reportfile.FileName);
                using (var fileStream = new FileStream(Path.Combine(newPath, fiName), FileMode.Create))
                {
                    reportfile.CopyTo(fileStream);
                }
                // Get uploaded file path with root
                string rootFolder = _hostingEnvironment.WebRootPath;
                string fileName = @"ImportedFiles/" + fiName;
                FileInfo file = new FileInfo(Path.Combine(rootFolder, fileName));

                using (ExcelPackage package = new ExcelPackage(file))
                {
                    ExcelWorksheet workSheet = package.Workbook.Worksheets[1];
                    int totalRows = workSheet.Dimension.Rows;
                    List<TravelInsuranceType> TravelInsuranceTypeList = new List<TravelInsuranceType>();
                    for (int i = 2; i <= totalRows; i++)
                    {
                        TravelInsuranceTypeList.Add(new TravelInsuranceType
                        {
                            Id = Guid.NewGuid(),
                            Code = workSheet.Cells[i, 1].Value.ToString(),
                            Name = workSheet.Cells[i, 2].Value.ToString(),
                            Description = workSheet.Cells[i, 3].Value.ToString(),
                            Term = workSheet.Cells[i, 4].Value.ToString(),
                            CreatedDate = DateTime.Now,
                            CreatedBy = "HninYee",
                            ModifiedDate = DateTime.Now,
                            ModifiedBy = "HninYee",
                            Active = true
                        });
                    }
                    _db.TravelInsuranceType.AddRange(TravelInsuranceTypeList);
                    _db.SaveChanges();
                    return RedirectToAction("TravelInsuranceType");
                }
            }
            
        }

        public IActionResult ExportTravelInsuranceTypeList()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                var travelInsuranceTypes = (from t1 in _db.TravelInsuranceType
                                            select new TravelInsuranceType
                                            {
                                                Name = t1.Name,
                                                Description = t1.Description,
                                                Term = t1.Term,
                                            }
                            ).ToList();


                var columnHeader = new List<string>
                {
                    "Code",
                    "Name",
                    "Descrption",
                    "Term",
                };

                var fileContent = ExportExcelForUserList(travelInsuranceTypes, columnHeader, "Test");
                return File(fileContent, "application/ms-excel", "TravelInsuranceTypeList.xlsx");
            }
        }

        public byte[] ExportExcelForUserList(List<TravelInsuranceType> travelInsuranceTypes, List<string> columnHeader, string heading)
        {
            byte[] result = null;
            using (ExcelPackage package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add(heading);
                worksheet.DefaultColWidth = 20;
                using (var cells = worksheet.Cells[1, 1, 1, 8])
                {
                    cells.Style.Font.Bold = true;
                }

                for (int i = 0; i < columnHeader.Count(); i++)
                {
                    worksheet.Cells[1, i + 1].Value = columnHeader[i];
                }
                var j = 2;
                var count = 1;
                foreach (var item in travelInsuranceTypes)
                {
                    worksheet.Cells["A" + j].Value = item.Code;
                    worksheet.Cells["B" + j].Value = item.Name;
                    worksheet.Cells["C" + j].Value = item.Description;
                    worksheet.Cells["D" + j].Value = item.Term;
                   
                    j++;
                    count++;
                }
                result = package.GetAsByteArray();
            }
            return result;
        }

        [Route("Delete")]

AMGI.PremiumCalculator.Project/Views/TravelSetup/CreatePremiumUnitAmount.cshtml
@model AMGI.PremiumCalculator.Project.Models.PremiumUnitAmount
@{
    ViewData["Title"] = "CreatePremiumUnitAmount";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}


@using (Html.BeginForm("SavePremiumUnitAmount", "TravelSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Travel Insurance Type</h3>
        </div>
        <div style="float:right;margin-right:30px;">
            <a href='@Url.Action("PremiumUnitAmountList","TravelSetup", null)' id="imgUserList">
                <img src="~/images/RoleList.png" />
            </a>

        </div>
    </div>

    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <font color="red">@TempData["Message"] </font>
    </div>

    <div class="row">
        <div class="form-horizontal" style="margin-left:30px;">

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Name", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Description", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Days", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Days, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Amount", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Travel Insurance Type", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @*@Html.TextBoxFor(model => model.TravelInsuranceTypeCode, new { @class = "form-control", @required = "required", autocomplete = "off" })*@
                    @Html.DropDownListFor(model => model.TravelInsuranceTypeCode, ViewBag.TravelInsuranceType as IEnumerable<SelectListItem>, " ", new { @class = "form-control" })
                </div>
            </div>

            <div class="col-md-3">

            </div>
            <div class="col-md-4">
                <button type="submit" class="btn" style="color:#A92028;">Save</button>
            </div>

        </div>


    </div>
    
}

AMGI.PremiumCalculator.Project/Views/TravelSetup/CreateTravelInsuranceType.cshtml
@model AMGI.PremiumCalculator.Project.Models.TravelInsuranceType
@{
    ViewData["Title"] = "CreateTravelInsuranceType";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}


@using (Html.BeginForm("SaveTravelInsuranceType", "TravelSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Travel Insurance Type</h3>
        </div>
        <div style="float:right;margin-right:30px;">
            <a href='@Url.Action("TravelInsuranceType","TravelSetup", null)' id="imgUserList">
                <img src="~/images/RoleList.png" />
            </a>

        </div>
    </div>
    
    @Html.HiddenFor(model => model.Id)
 
    <div class="row">
        <font color="red">@TempData["Message"] </font>
    </div>

    <div class="row">
        <div class="form-horizontal" style="margin-left:30px;">

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Code", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Name", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Description", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Term", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Term, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Active", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @*@Html.TextBoxFor(model => model.Active, new { @class = "form-control", @required = "required", autocomplete = "off" })*@
                    @Html.CheckBoxFor(model => model.Active, new { @class = "checkbox" })
                </div>
            </div>

            <div class="col-md-3">

            </div>
            <div class="col-md-4">
                <button type="submit" class="btn" style="color:#A92028;">Save</button>
            </div>

        </div>


    </div>



}

AMGI.PremiumCalculator.Project/Views/TravelSetup/ImportPremiumUnitAmountList.cshtml
@{
    ViewData["Title"] = "ImportPremiumUnitAmountList";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">
            Import Premium Unit Amount List
        </h3>
    </div>
</div>

@using (Html.BeginForm("ImportPremiumUnitAmountListExcelData", "TravelSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*<p>Excel File : </p>
        <input type="file" class="btn btn-danger" name="excelfile" />
        <button type="submit" class="btn" style="color:#A92028;">Upload</button>*@
    <div class="row">
        <div class="col-md-4">
            <input type="file" id="reportfile" name="reportfile" class="form-control" />
        </div>
        <div class="col-md-8">
            <input type="submit" id="btnUpload" value="Upload" class="btn" style="color:#A92028;" />
        </div>
    </div>

}

AMGI.PremiumCalculator.Project/Views/TravelSetup/ImportTravelInsuranceTypeList.cshtml
@{
    ViewData["Title"] = "ImportTravelInsuranceTypeList";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

@*<script>

        $('document').ready(function () {

            $('#btnUpload').click(function () {

                var formData = new FormData($('form')[0]);

                $('#mdlSuccess').modal('hide');
                $('#mdlInvalid').modal('hide');
                $('#pSuccess').html("");
                $('#pInvalid').html("");

                $.ajax({
                    url: '/TravelSetup/ImportExcel',
                    type: "POST",
                    dataType: "JSON",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (fnStockClass) {

                        if (fnStockClass.RetCode == 0) {
                            $('#mdlInvalid').modal('show');
                            $('#pInvalid').html(fnStockClass.RetMessage);

                        }

                        else {
                            var tableContent = "";

                            $.each(fnStockClass.StockClassList, function (i, stockClass) {

                                var itemLenght = $('tr[title = "StockInfo"]').length;
                                tableContent += "<tr><td>" + stockClass.StockClassCode + "</td><td>" + stockClass.StockClassName + "</td><td>" + stockClass.StockClassDescription + "</td>";
                                if (stockClass.IsStock)
                                {
                                    tableContent += "<td style='text-align:center'><input type='checkbox' checked='checked' disabled='disabled name='IsStock' /></td>";
                                }
                                else
                                {
                                    tableContent += "<td style='text-align:center'><input type='checkbox' disabled='disabled name='IsStock' /></td>";
                                }
                                if (stockClass.Active) {
                                    tableContent += "<td style='text-align:center'><input type='checkbox' checked='checked' disabled='disabled name='Active' /></td>";
                                }
                                else {
                                    tableContent += "<td style='text-align:center'><input type='checkbox' disabled='disabled name='Active' /></td>";
                                }
                                tableContent += "</tr>";

                            });
                            $('#tBodyStockClassInfo').html(tableContent);
                        }
                    }
                });


            });

            $('#btnSuccessOk').click(function () {

                window.location.href = "/StockClass/Create";

            });

            $('#btnSave').click(function () {

                $('#mdlSuccess').modal('hide');
                $('#mdlInvalid').modal('hide');
                $('#pSuccess').html("");
                $('#pInvalid').html("");


                $.ajax({
                    url: '@Url.Action("SaveExcelData", "StockClass")',
                    type: "POST",
                    dataType: "JSON",
                    contentType: "application/json",
                    success: function (returnMessage) {

                        if (returnMessage.RetCode > 0) {

                            $('#mdlSuccess').modal('show');
                            $('#pSuccess').html(returnMessage.RetMessage);
                            var successCode = "'" + stockClassCode + "'";
                            $('#bSuccessCode').html(successCode);
                        }
                        else {
                            $('#mdlInvalid').modal('show');
                            $('#pInvalid').html(returnMessage.RetMessage);
                        }

                    }

                });
            });
        });

    </script>*@


<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">
            Import Travel Insurance Type List
        </h3>
    </div>
</div>

@using (Html.BeginForm("ImportExcelData", "TravelSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*<p>Excel File : </p>
        <input type="file" class="btn btn-danger" name="excelfile" />
        <button type="submit" class="btn" style="color:#A92028;">Upload</button>*@
    <div class="row">
        <div class="col-md-4">
            <input type="file" id="reportfile" name="reportfile" class="form-control" />
        </div>
        <div class="col-md-8">
            <input type="submit" id="btnUpload" value="Upload" class="btn" style="color:#A92028;" />
        </div>
    </div>
    
}

AMGI.PremiumCalculator.Project/Views/TravelSetup/PremiumUnitAmount.cshtml
@{
    ViewData["Title"] = "PremiumUnitAmount";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<h2>PremiumUnitAmount</h2>

AMGI.PremiumCalculator.Project/Views/TravelSetup/PremiumUnitAmountList.cshtml
@model AMGI.PremiumCalculator.Project.Models.PremiumUnitAmountViewModel
@{
    ViewData["Title"] = "PremiumUnitAmountList";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">
            Premium Unit Amount List
        </h3>
    </div>
</div>

<div class="row">
    <ul class="nav navbar-right panel_toolbox" style="margin-right:20px;">
        <li style="float:left;display:none;">
            <a href='@Url.Action("CreatePremiumUnitAmountList", "TravelSetup", null)'><i class="fa fa-plus" style="font-size:30px;"></i></a>
        </li>

        <li class="dropdown" style="float:left;">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-file-excel-o" style="font-size:30px;"></i></a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href='@Url.Action("ExportPremiumUnitAmountList", "TravelSetup", null)'><i class="fa fa-download"></i> Export</a>
                </li>
                <li>
                    <a href="@Url.Action("ImportPremiumUnitAmountList", "TravelSetup")" id="btnImport"><i class="fa fa-upload"></i> Import</a>
                </li>
            </ul>
        </li>

    </ul>
    <div class="clearfix"></div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy-datatable">
                    <thead>
                        <tr>
                            <th>NAME</th>
                            <th>DESCRIPTION</th>
                            <th>DAYS</th>
                            <th>AMOUNT</th>
                            <th>
                                TRAVELINSURANCETYPE
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var premiumUnitAmount in (List<PremiumUnitAmountViewModel>)ViewBag.PremiumUnitAmountList)
                        {
                        <tr class="odd gradeX">
                            <td>@premiumUnitAmount.Name</td>
                            <td>@premiumUnitAmount.Description</td>
                            <td>@premiumUnitAmount.Days</td>
                            <td>@premiumUnitAmount.Amount</td>
                            <td>@premiumUnitAmount.TravelInsuranceTypeName</td>

                            <td style="text-align:center;">
                                <a href='@Url.Action("EditPremiumUnitAmount", "TravelSetup", new { Id = @premiumUnitAmount.Id })'>
                                    <img src="~/images/Edit.png" />
                                </a>
                            </td>

                            <td style="text-align:center;">
                                <a href='@Url.Action("DeletePremiumUnitAmountAsync", "TravelSetup", new { @Id = @premiumUnitAmount.Id })' onclick="return confirm('Are you sure you want to delete this item?');">
                                    <img src="~/images/remove.png" />
                                </a>
                            </td>

                        </tr>
                        }
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
                <!-- /.table-responsive -->
            </div>
        </div>
    </div>
</div>