AMGI.PremiumCalculator.Project/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AMGI.PremiumCalculator.Project.Models
{
    public class Branch
    {
        public Guid BranchId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public bool? Active { get; set; }
    }
}

AMGI.PremiumCalculator.Project/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMGI.PremiumCalculator.Project.Models
{
    public class Department
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

AMGI.PremiumCalculator.Project/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMGI.PremiumCalculator.Project.Models
{
    public class Product
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    }
}

AMGI.PremiumCalculator.Project/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AMGI.PremiumCalculator.Project.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;

namespace AMGI.PremiumCalculator.Project.Controllers
{
    public class SetupController : Controller
    {
        public ISession session;
        private readonly IHostingEnvironment _hostingEnvironment;

        public SetupController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }


        MainDBContext _db = new MainDBContext();

        #region Branch

        public IActionResult Branch()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                ViewBag.BranchList = _db.Branch.ToList();
                return View(new Branch());
            }
        }

        [HttpPost]
        public IActionResult Branch(Branch model)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                if (model == null || model.Name == null)
                {
                    TempData["Message"] = "Please enter the name.";
                }
                else
                {
                    if (model.BranchId == Guid.Empty)
                    {
                        model.BranchId = Guid.NewGuid();
                        model.Name = model.Name.ToUpper();
                        _db.Entry(model).State = EntityState.Added;
                        _db.SaveChanges();
                        ViewBag.Message = "Save Successful.";
                    }
                    else
                    {
                        if (ModelState.IsValid)
                        {
                            _db.Update(model);
                            _db.SaveChanges();
                            ViewBag.Message = "Update Successful.";
                        }
                        else
                        {
                            ViewBag.Message = "Error in Update Process.";
                        }
                    }
                }
            }
            ViewBag.BranchList = _db.Branch.ToList();
            return RedirectToAction("Branch");
        }

        public IActionResult EditBranch(Guid branchId)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                Branch branch = _db.Branch.Where(r => r.BranchId == branchId).FirstOrDefault();
                ViewBag.BranchList = _db.Branch.ToList();
                return View("Branch", branch);
            }
        }

        public IActionResult DeleteBranch(Guid branchId)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                var branch = _db.Branch.AsNoTracking().SingleOrDefault(m => m.BranchId == branchId);
                if (branch == null)
                {
                    return RedirectToAction(nameof(Branch));
                }
                try
                {
                    var userList = _db.SysUser.Where(u => u.Branch == branchId).ToList();
                    if (userList.Count == 0)
                    {
                        _db.Branch.Remove(branch);
                        _db.SaveChanges();
                        return RedirectToAction("Branch", new Branch());
                    }
                    else
                    {
                        TempData["Message"] = "This branch has already used in process.";
                    }
                    ViewBag.BranchList = _db.Branch.ToList();
                    return RedirectToAction("Branch", null);

                }
                catch (DbUpdateException)
                {
                    return View("Branch", new { id = branchId, saveChangesError = true });
                }
            }

        }

        #endregion

        #region Department
        public IActionResult Department()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                ViewBag.DepartmentList = _db.Department.ToList();
                return View(new Department());
            }
        }

        [HttpPost]
        public IActionResult Department(Department model)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                if (model == null || model.Name == null)
                {
                    TempData["Message"] = "Please enter the name.";
                }
                else
                {
                    if (model.Id == Guid.Empty)
                    {
                        model.Id = Guid.NewGuid();
                        model.Name = model.Name.ToUpper();
                        _db.Entry(model).State = EntityState.Added;
                        _db.SaveChanges();
                        ViewBag.Message = "Save Successful.";
                    }
                    else
                    {
                        if (ModelState.IsValid)
                        {
                            _db.Update(model);
                            _db.SaveChanges();
                            ViewBag.Message = "Update Successful.";
                        }
                        else
                        {
                            ViewBag.Message = "Error in Update Process.";
                        }
                    }
                }
            }
            ViewBag.DepartmentList = _db.Department.ToList();
            return RedirectToAction("Department");
        }

        public IActionResult EditDepartment(Guid deptId)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                Department dept = _db.Department.Where(r => r.Id == deptId).FirstOrDefault();
                ViewBag.DepartmentList = _db.Department.ToList();
                return View("Department", dept);
            }
        }

        public IActionResult DeleteDepartment(Guid deptId)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                var department = _db.Department.AsNoTracking().SingleOrDefault(m => m.Id == deptId);
                if (department == null)
                {
                    return RedirectToAction(nameof(Department));
                }
                try
                {
                    var userList = _db.SysUser.Where(u => u.Department == deptId).ToList();
                    if (userList.Count == 0)
                    {
                        _db.Department.Remove(department);
                        _db.SaveChanges();
                        return RedirectToAction("Department", new Department());
                    }
                    else
                    {
                        TempData["Message"] = "This department has already used in process.";
                    }
                    ViewBag.DepartmentList = _db.Department.ToList();
                    return RedirectToAction("Department", null);

                }
                catch (DbUpdateException)
                {
                    return View("Branch", new { id = deptId, saveChangesError = true });
                }
            }

        }

        #endregion

        #region Product

        public IActionResult Product()
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                Product Product = new Product();
                var ProductList = _db.Product.ToList();
                ViewBag.ProductList = ProductList;
                return View();
            }
        }

        public IActionResult CreateProduct(Product product)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult SaveProduct(Product model)
        {
            session = HttpContext.Session;
            if (string.IsNullOrEmpty(session.GetString("username")))
                return RedirectToAction("Login", "Account");
            else
            {
                try
                {
                    if (model.Id == Guid.Empty)
                    {
                        model.Id = Guid.NewGuid();
                        model.CreatedDate = DateTime.Now;
                        model.ModifiedDate = DateTime.Now;
                        session = HttpContext.Session;

AMGI.PremiumCalculator.Project/Views/Setup/Branch.cshtml
@model Branch
@{
    ViewData["Title"] = "Branch";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

@using (Html.BeginForm("Branch", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">Branch</h1>
        </div>
        @Html.HiddenFor(model => model.BranchId)
        <font color="red">@TempData["Message"]</font>
        <div class="col-md-12">
            <div class="col-md-4">
                <div class="wrap-input100 validate-input" data-validate="Name is required">
                    <span class="label-input100">Name</span>
                    <input class="input100" type="text" name="Name" asp-for="Name" placeholder="Enter Name">
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Description</span>
                    <input class="input100" type="text" name="Description" asp-for="Description" placeholder="Enter Description">
                    <span class="focus-input100"></span>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Address</span>
                    <input class="input100" type="text" name="Address" asp-for="Address" placeholder="Enter Address" multiple>
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-6" style="margin-top:35px;">
                <div class="col-md-2">
                    <a href='@Url.Action("Branch","Setup", null)' class="btn btn-default">
                        <i class="fa fa-plus"></i>
                        New
                    </a>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                        <i class="fa fa-save"></i>
                        Save
                    </button>
                </div>
                <div class="col-md-2">
                    <a href='@Url.Action("DeleteBranch","Setup", new { @branchId = Model.BranchId})' id="btnDelete" class="btn btn-default" onclick="return confirm('Are you sure you want to delete?')">
                        <i class="fa fa-cut"></i>
                        Delete
                    </a>
                </div>
                <div class="col-md-6">
                    <font color="red"> @TempData["Message"]</font>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <br />
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy-datatable">
                        <thead>
                            <tr>
                                <th>NAME</th>
                                <th>DESCRIPTION</th>
                                <th>ADDRESS</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var branch in (List<Branch>)ViewBag.BranchList)
                            {
                                <tr class="odd gradeX">
                                    <td>@branch.Name</td>
                                    <td>@branch.Description</td>
                                    <td>@branch.Address</td>
                                    <td style="text-align:center;">
                                        <a href='@Url.Action("EditBranch", "Setup", new { @branchId = @branch.BranchId })'>
                                            <img src="~/images/Edit.png" />
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

s

AMGI.PremiumCalculator.Project/Views/Setup/CreateProduct.cshtml
@model Product
@{
    ViewData["Title"] = "CreateProduct";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

@using (Html.BeginForm("SaveProduct", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Travel Insurance Type</h3>
        </div>
        <div style="float:right;margin-right:30px;">
            <a href='@Url.Action("Product","Setup", null)' id="imgUserList">
                <img src="~/images/RoleList.png" />
            </a>

        </div>
    </div>

    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <font color="red">@TempData["Message"]</font>
    </div>

    <div class="row">
        <div class="form-horizontal" style="margin-left:30px;">

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Name", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("Description", null, new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @required = "required", autocomplete = "off" })
                </div>
            </div>

            <div class="col-md-3">

            </div>
            <div class="col-md-4">
                <button type="submit" class="btn" style="color:#A92028;">Save</button>
            </div>

        </div>


    </div>
    
}

AMGI.PremiumCalculator.Project/Views/Setup/Department.cshtml
@model Department
@{
    ViewData["Title"] = "Department";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

@using (Html.BeginForm("Department", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    <div class="col-md-12">
        <h1 class="page-header">Branch</h1>
    </div>
    @Html.HiddenFor(model => model.Id)
    <font color="red">@TempData["Message"]</font>
    <div class="col-md-12">
        <div class="col-md-4">
            <div class="wrap-input100 validate-input" data-validate="Name is required">
                <span class="label-input100">Name</span>
                <input class="input100" type="text" name="Name" asp-for="Name" placeholder="Enter Name">
                <span class="focus-input100"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="wrap-input100 validate-input">
                <span class="label-input100">Description</span>
                <input class="input100" type="text" name="Description" asp-for="Description" placeholder="Enter Description">
                <span class="focus-input100"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6" style="margin-top:35px;">
        <div class="col-md-2">
            <a href='@Url.Action("Branch","Setup", null)' class="btn btn-default">
                <i class="fa fa-plus"></i>
                New
            </a>
        </div>
        <div class="col-md-2">
            <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                <i class="fa fa-save"></i>
                Save
            </button>
        </div>
        <div class="col-md-2">
            <a href='@Url.Action("DeleteBranch","Setup", new { @deptId = Model.Id})' id="btnDelete" class="btn btn-default" onclick="return confirm('Are you sure you want to delete?')">
                <i class="fa fa-cut"></i>
                Delete
            </a>
        </div>
        <div class="col-md-6">
            <font color="red"> @TempData["Message"]</font>
        </div>
    </div>

    <div class="col-md-12">
        <br />
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy-datatable">
                    <thead>
                        <tr>
                            <th>NAME</th>
                            <th>DESCRIPTION</th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var dept in (List<Department>)ViewBag.DepartmentList)
                        {
                            <tr class="odd gradeX">
                                <td>@dept.Name</td>
                                <td>@dept.Description</td>
                                <td style="text-align:center;">
                                    <a href='@Url.Action("EditDepartment", "Setup", new { @deptId = dept.Id })'>
                                        <img src="~/images/Edit.png" />
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
}

AMGI.PremiumCalculator.Project/Views/Setup/ImportProductList.cshtml
@{
    ViewData["Title"] = "ImportProductList";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">
            Import Travel Insurance Type List
        </h3>
    </div>
</div>

@using (Html.BeginForm("ImportExcelData", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*<p>Excel File : </p>
        <input type="file" class="btn btn-danger" name="excelfile" />
        <button type="submit" class="btn" style="color:#A92028;">Upload</button>*@
    <div class="row">
        <div class="col-md-4">
            <input type="file" id="reportfile" name="reportfile" class="form-control" />
        </div>
        <div class="col-md-8">
            <input type="submit" id="btnUpload" value="Upload" class="btn" style="color:#A92028;" />
        </div>
    </div>

}

AMGI.PremiumCalculator.Project/Views/Setup/Product.cshtml
@model Product
@{
    ViewData["Title"] = "Product";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">
            Product List
        </h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12" style="border:1px solid red;">
        <font color="red">@TempData["Message"]</font>
    </div>
    <ul class="nav navbar-right panel_toolbox" style="margin-right:20px;">

        <li style="float:left;display:none;">
            <a href='@Url.Action("CreateProduct", "Setup", null)'><i class="fa fa-plus" style="font-size:30px;"></i></a>
        </li>

        <li class="dropdown" style="float:left;">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-file-excel-o" style="font-size:30px;"></i></a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href='@Url.Action("ExportProductList", "Setup", null)'><i class="fa fa-download"></i> Export</a>
                </li>
                <li>
                    <a href="@Url.Action("ImportProductList", "Setup")" id="btnImport"><i class="fa fa-upload"></i> Import</a>
                </li>
            </ul>
        </li>

    </ul>
    <div class="clearfix"></div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy-datatable">
                    <thead>
                        <tr>
                            <th>NAME</th>
                            <th>DESCRIPTION</th>
                            <th>EDIT</th>
                            <th>DELETE</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in (List<Product>)ViewBag.ProductList)
                        {
                        <tr class="odd gradeX">
                            <td>@product.Name</td>
                            <td>@product.Description</td>
                            <td style="text-align:center;">
                                <a href='@Url.Action("EditProduct", "Setup", new { Id = @product.Id })'>
                                    <img src="~/images/Edit.png" />
                                </a>
                            </td>
                            <td style="text-align:center;">
                                <a href='@Url.Action("DeleteProductAsync", "Setup", new { @Id = @product.Id })' onclick="return confirm('Are you sure you want to delete this item?');">
                                    <img src="~/images/remove.png" />
                                </a>
                            </td>

                        </tr>
                        }
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
                <!-- /.table-responsive -->
            </div>
        </div>
    </div>
</div>